Use circuit-params feature and use CurveAffineExt from halo2_base
scroll-tech/snark-verifier pull request #36
Opened 2024-06-24 06:57 UTC by z2trillion

2024-08-13 09:24 UTC, roynalnaruto requested changes
Small comment on error handling, looks good otherwise

2024-08-13 09:24 UTC, roynalnaruto commented on snark-verifier-sdk/src/file_io.rs
> +        ProvingKey::read::<_, C>(&mut bufreader, SerdeFormat::RawBytesUnchecked, params).unwrap();
`ProvingKey::Read` is fallible and already returns `std::io::Result` we should handle the error here:
```suggestion
        ProvingKey::read::<_, C>(&mut bufreader, SerdeFormat::RawBytesUnchecked, params)?;
```

2024-08-15 17:33 UTC, roynalnaruto requested changes
Not compiling:

```
error[E0437]: type `Params` is not a member of trait `Circuit`
   --> snark-verifier-sdk/src/aggregation/aggregation_circuit.rs:132:5
    |
132 |     type Params = ();
    |     ^^^^^^^^^^^^^^^^^ not a member of trait `Circuit`

error[E0437]: type `Params` is not a member of trait `Circuit`
  --> snark-verifier-sdk/src/aggregation/multi_aggregation_circuit.rs:89:5
   |
89 |     type Params = ();
   |     ^^^^^^^^^^^^^^^^^ not a member of trait `Circuit`

error[E0437]: type `Params` is not a member of trait `Circuit`
  --> snark-verifier-sdk/src/snark/mock.rs:34:5
   |
34 |     type Params = ();
   |     ^^^^^^^^^^^^^^^^^ not a member of trait `Circuit`

error[E0220]: associated type `Params` not found for `C`
  --> snark-verifier-sdk/src/file_io.rs:50:16
   |
50 |     params: C::Params,
   |                ^^^^^^ associated type `Params` not found

Some errors have detailed explanations: E0220, E0437.
```

2024-09-03 02:14 UTC, lispc approved these changes

2024-09-05 06:16 UTC, merged